apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: otel-http-ingress
  namespace: telemetry
spec:
  entryPoints:
    - otlp-http
  routes:
    - match: PathPrefix(`/v1/traces`)
      kind: Rule
      services:
        - name: opentelemetry-collector
          port: 4318
